### ISSUE TITLE
Selecting a category filter

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_F#133]
### Scenario: 
  
  - User can select a category to filter recipes
    
    ### Given: 
    
    - I am on the recipes list page
    
    ### When: 
    
    - I select a specific category from the category filter
    
    ### Then: 
    
    - The filter should be applied to the recipes list

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by Kenneth-Ngcobo** [comment]
Add a selectable suggestion dropdown menu of all available categories
