### ISSUE TITLE
Display of Allergens in Recipe Description

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_F#9]
### SCENARIO: 
  
  - Display of allergen information in recipe description
    
    ### GIVEN: 
    
    - I am viewing the list of recipe previews
    
    ### WHEN: 
    
    - I navigate to a specific recipe page
    
    ### THEN: 
    
    - Any allergens present in the recipe should be clearly indicated in the description

**Comment by Kenneth-Ngcobo** [comment]
Teams use the list of common allergens from DB to filter out recipes with ingredients that match anything on the list.
